### ISSUE TITLE
An asynchronous operation cannot be started at this time

### ISSUE THREAD

**Issue by dchaib** [influxdata/influxdb-csharp#15]
I am trying to use the batch feature to track page views in an ASP application. I am emitting new mesurements in `Application_EndRequest` and I get this error:

> An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.

Am I trying to do something that is impossible/unsupported? Is there another way of doing it? Do we need to update `PortableTimer`?

**Comment by nblumhardt** [comment]
Thank you for the report; I haven't seen this one before so it might need some investigation.

I'm planning to update the library for .NET Core 1.0 today if time permits, so that should make the development experience a little smoother if you want to dig in.

**Comment by dchaib** [comment]
I have looked into this some more and I don't believe this is linked in any way to this library. I'm closing the issue.

**Comment by tukaef** [comment]
Hi,

Seems like the issue is still here...

> Failed to write point 
System.InvalidOperationException: An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.
   at System.Web.AspNetSynchronizationContext.OperationStarted()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Create()
   at InfluxDB.Collector.Platform.PortableTimer.Start(TimeSpan interval)
   at InfluxDB.Collector.Pipeline.Batch.IntervalBatcher.Emit(PointData[] points)
   at InfluxDB.Collector.Pipeline.PipelinedMetricsCollector.Emit(PointData[] points)
   at InfluxDB.Collector.MetricsCollector.InfluxDB.Collector.Pipeline.IPointEmitter.Emit(PointData[] points)
   at InfluxDB.Collector.Pipeline.PipelinedMetricsCollector.Emit(PointData[] points)
   at InfluxDB.Collector.MetricsCollector.Write(String measurement, IReadOnlyDictionary`2 fields, IReadOnlyDictionary`2 tags, Nullable`1 timestamp)

Workaround is setting `aspnet:UseTaskFriendlySynchronizationContext` to `false`

**Comment by nblumhardt** [comment]
Thanks for the note @tukaef. I am not certain of the root cause of this, but I do know that Serilog's portable timer implementation has been through a few rounds of modification and now uses a different approach:

https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PortableTimer.cs

If anyone is able to test out the Serilog version of the timer, and PR it in to replace `PortableTimer` here, I think it would be a safe change to make.

**Comment by tukaef** [comment]
Serilog's timer works fine for me.
