### ISSUE TITLE
Can PseudoHighResTimestampSource be made lock free?

### ISSUE THREAD

**Issue by cypressious** [influxdata/influxdb-csharp#57]
I'm not the greatest expert in concurrent code but can we somehow get rid of the lock by using `Interlocked`?

**Comment by optical** [comment]
Check out #47, we discussed the possibility of using lock vs interlocked there. The benchmarks run showed interlocked was marginally faster then lock in low contention scenarios, but significantly worse with higher concurrency.

Replacing with interlocked would probably need some additional benchmark samples and reasoning in order to put forward a compelling case.

**Comment by cypressious** [comment]
Thanks for the link. I'm closing this.
